config/routes.rb
PasseLivre::Application.routes.draw do
  resources :pessoas
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]

  root 'sessions#new'

  match '/login',   to: 'sessions#new',     via: 'get'
  match '/logoff',  to: 'sessions#destroy', via: 'delete'

end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
	validates :nome, presence: true
	validates :rg, presence: true, uniqueness: true
	validates :cpf, presence: true, uniqueness: true
	validates :data_nasc, presence: true
	validates :endereco, presence: true
	validates :numero, presence: true
	validates :bairro, presence: true
	validates :cidade, presence: true
	validates :estado, presence: true
	validates :cid, presence: true
	validates :descr_deficiencia, presence: true
	validates :emissor_laudo, presence: true
	validates :registro_emissor, presence: true
	validates :data_laudo, presence: true

	def getDataExpiracao
		if(self.data_expiracao.to_s.empty?)
			return (self.updated_at + 2.years).to_s(:data_abreviada)
		end

		self.data_expiracao.to_s(:data_abreviada)
	end
end

app/controllers/pessoas_controller.rb
# encoding: UTF-8

class PessoasController < ApplicationController

	def index
		@pessoas = Pessoa.order("nome").paginate(page: params[:page])
	end

	def show
		@pessoa = Pessoa.find(params[:id])
		respond_to do |formato|
			formato.html
			formato.pdf do
				pdf = PessoaPdf.new(@pessoa, view_context)
				send_data pdf.render, filename:
					"credencial_#{@pessoa.rg}_#{@pessoa.created_at.strftime("%d-%m-%Y")}.pdf",
					type: "application/pdf"
			end
		end
	end

	def new
		@pessoa = Pessoa.new
	end

	def create
		@pessoa = Pessoa.new(pessoa_params)
		if @pessoa.save
			redirect_to @pessoa
		else
			render 'new'
		end
	end

	def edit
		@pessoa = Pessoa.find(params[:id])
	end

	def update
		@pessoa = Pessoa.find(params[:id])
		if @pessoa.update_attributes(pessoa_params)
			redirect_to @pessoa
		else
			render 'edit'
		end
	end

	def destroy
		Pessoa.find(params[:id]).destroy
		redirect_to pessoas_url
	end

	private
		def pessoa_params
			params.require(:pessoa).permit(:nome, :rg, :cpf, :data_nasc,
				:pai, :mae, :endereco, :numero, :complemento, :bairro,
				:cidade, :estado, :telefone, :cid, :descr_deficiencia,
				:emissor_laudo, :registro_emissor, :data_laudo,
				:acompanhante, :acomp_nome, :acomp_rg, :acomp_cpf, :data_expiracao)
		end
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/pessoas/_campos.html.erb
	<%= render 'shared/error_messages' %>

	<%= f.label :nome %>
	<%= f.text_field :nome %><br>

	<%= f.label :rg, "RG" %>
	<%= f.text_field :rg %><br>

	<%= f.label :cpf, "CPF" %>
	<%= f.text_field :cpf %><br>

	<%= f.label :data_nasc, "Data de nascimento" %>
	<%= f.text_field :data_nasc,
		value: @pessoa.data_nasc ? @pessoa.data_nasc.to_s(:data_abreviada) : "" %><br>

	<%= f.label :pai, "Nome do pai" %>
	<%= f.text_field :pai %><br>

	<%= f.label :mae, "Nome da mãe" %>
	<%= f.text_field :mae %><br>

	<%= f.label :endereco, "Endereço" %>
	<%= f.text_field :endereco %><br>

	<%= f.label :numero, "Número" %>
	<%= f.text_field :numero %><br>

	<%= f.label :complemento %>
	<%= f.text_field :complemento %><br>

	<%= f.label :bairro %>
	<%= f.text_field :bairro %><br>

	<%= f.label :cidade %>
	<%= f.text_field :cidade %><br>

	<%= f.label :estado %>
	<%= f.text_field :estado %><br>

	<%= f.label :telefone %>
	<%= f.text_field :telefone %><br>

	<%= f.label :cid, "CID" %>
	<%= f.text_field :cid %><br>

	<%= f.label :descr_deficiencia, "Descrição da deficiência" %>
	<%= f.text_field :descr_deficiencia %><br>

	<%= f.label :emissor_laudo, "Emissor do laudo" %>
	<%= f.text_field :emissor_laudo %><br>

	<%= f.label :registro_emissor, "Registro do emissor" %>
	<%= f.text_field :registro_emissor %><br>

	<%= f.label :data_laudo, "Data do laudo" %>
	<%= f.text_field :data_laudo,
		value: @pessoa.data_laudo ? @pessoa.data_laudo.to_s(:data_abreviada) : "" %><br>

	<%= f.label :data_expiracao, "Data vencimento" %>
		<%= f.text_field :data_expiracao,
			value: @pessoa.data_expiracao ? @pessoa.data_expiracao.to_s(:data_abreviada) : "" %><br>

	<%= f.label :acompanhante, "Acompanhante autorizado:" %>
	<%= f.check_box :acompanhante, :onclick => "acompanhantePessoaCheckboxClick(event, this)" %><br>
	<% acompanhantesContainerDisplay = @pessoa.data_expiracao ? 'block' : 'none' %>
		Dados Acompanhante

		<%= f.label :acomp_nome, "Nome" %>
			<%= f.text_field :acomp_nome %><br>

app/views/pessoas/_pessoa.html.erb
<li>
	<%= link_to "#{pessoa.nome} [Data Nasc: #{pessoa.data_nasc}, RG: #{pessoa.rg}]" , pessoa %>
</li>

app/views/pessoas/edit.html.erb
<% provide :titulo, "Pessoas (Alteração)" %>
<% content_for :botoes do %>
	<li><%= link_to "Listar", pessoas_path %></li>
	<li><%= link_to "Adicionar", new_pessoa_path %></li>
<% end %>
<div class="center">
	<%= form_for(@pessoa) do |f| %>

		<%= render 'campos', f: f %>
		<br>
		<%= f.submit "Gravar", class: "btn" %> 
		<%= link_to "Cancelar", @pessoa, class: "btn" %>
	<% end %>
</div>

app/views/pessoas/index.html.erb
<% provide :titulo, "Pessoas" %>
<% content_for :botoes do %>
		<li><%= link_to "Adicionar", new_pessoa_path %></li>
<% end %>
<ul>
	<%= render @pessoas %>
</ul>
<%= will_paginate %>

app/views/pessoas/new.html.erb
<% provide :titulo, "Pessoas (Novo)" %>
<% content_for :botoes do %>
	<li><%= link_to "Listar", pessoas_path %></li>
	<li><%= link_to "Adicionar", new_pessoa_path %></li>
<% end %>
<%= form_for(@pessoa) do |f| %>

	<%= render 'campos', f: f %>
	
	<br>
	<%= f.submit "Gravar" %>
	<%= link_to "Cancelar", pessoas_path %>
<% end %>

app/views/pessoas/show.html.erb
# encoding: UTF-8

<% provide :titulo, "Pessoas (Detalhes)" %>
<% content_for :botoes do %>
	<li><%= link_to "Listar", pessoas_path %></li>
	<li><%= link_to "Adicionar", new_pessoa_path %></li>
	<li><%= link_to "Excluir", @pessoa, method: :delete,
		data: { confirm: "Tem certeza que deseja excluir '#{@pessoa.nome}'?" } %></li>
	<li><%= link_to "Alterar", edit_pessoa_path(params[:id]) %></li>
	<li><%= link_to "Imprimir", pessoa_path(@pessoa.id, format: "pdf") %></li>
<% end %>

Nome: <%= @pessoa.nome %><br>
RG: <%= @pessoa.rg %><br>
CPF: <%= @pessoa.cpf %><br>
Data de Nascimento: <%= @pessoa.data_nasc.to_s(:data_abreviada) %><br>
Nome do Pai: <%= @pessoa.pai %><br>
Nome da Mãe: <%= @pessoa.mae %><br>
Endereço: <%= @pessoa.endereco %><br>
Número: <%= @pessoa.numero %><br>
Complemento: <%= @pessoa.complemento %><br>
Bairro: <%= @pessoa.bairro %><br>
Cidade: <%= @pessoa.cidade %><br>
Estado: <%= @pessoa.estado %><br>
Telefone: <%= @pessoa.telefone %><br>
CID: <%= @pessoa.cid %><br>
Descrição da Deficiência: <%= @pessoa.descr_deficiencia %><br>
Emissor do Laudo: <%= @pessoa.emissor_laudo %><br>
Registro do Emissor: <%= @pessoa.registro_emissor %><br>
Data do Laudo: <%= @pessoa.data_laudo.to_s(:data_abreviada) %><br>
Acompanhante autorizado: <%= (@pessoa.acompanhante? ? 'Sim' : 'Não') %><br>

<% if @pessoa.acompanhante? %>
	Dados Acompanhante <br>
	Nome: <%= @pessoa.acomp_nome %><br>
<% end %>

Última Alteração/emissão: <%= @pessoa.updated_at.to_s(:data_abreviada) %><br>
Valido até: <%= @pessoa.getDataExpiracao %>