config/routes.rb
PasseLivre::Application.routes.draw do
  resources :pessoas
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]

  root 'sessions#new'

  match '/login',   to: 'sessions#new',     via: 'get'
  match '/logoff',  to: 'sessions#destroy', via: 'delete'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	before_save { self.nome = nome.downcase }

	validates :nome, presence: true, length: { maximum: 25 },
		uniqueness: { case_sensitive: false }
	validates :nome_completo, presence: true

	has_secure_password
	validates :password_confirmation, presence: true
	validates :password, length: { minimum: 4 }
end

app/controllers/usuarios_controller.rb
# encoding: UTF-8

class UsuariosController < ApplicationController
	before_action :usuario_admin

	def index
		@usuarios = Usuario.all
	end

	def show
		@usuario = Usuario.find(params[:id])
	end

	def new
		@usuario = Usuario.new
	end

	def create
		@usuario = Usuario.new(usuario_params)
		if @usuario.save
			flash[:success] = "Usuário criado com sucesso."
			redirect_to @usuario
		else
			render 'new'
		end

	end

	def edit
		@usuario = Usuario.find(params[:id])
	end

	def update
		@usuario = Usuario.find(params[:id])
		if @usuario.update_attributes(usuario_params)
			flash[:success] = "Alterações salvas."
			redirect_to @usuario
		else
			render 'edit'
		end

	end

	def destroy
		Usuario.find(params[:id]).destroy
		flash[:success] = "Usuário excluído."
		redirect_to usuarios_url
	end

	private
		def usuario_params
			params.require(:usuario).permit(:nome, :nome_completo, :password, :password_confirmation)
		end

		def usuario_admin
			redirect_to root_path,
				notice: "Somente administradores podem gerenciar usuários" unless usuario_atual.admin?
		end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_error_messages.html.erb
<% if @usuario.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			O formulário contém <%= pluralize(@usuario.errors.count, "erro") %>.
		</div>
		<ul>
			<% @usuario.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/usuarios/edit.html.erb
<% provide :titulo, "Usuários (Alteração)" %>
<% content_for :botoes do %>
	<li><%= link_to "Listar", usuarios_path %></li>
	<li><%= link_to "Adicionar", new_usuario_path %></li>
<% end %>

<%= form_for(@usuario) do |f| %>

	<%= render 'error_messages' %>

	<%=  f.label :nome %>
	<%=  f.text_field :nome %><br>

	<%= f.label :nome_completo %>
	<%= f.text_field :nome_completo %><br>

	<%= f.label :password %>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %><br>

	<%= f.submit "Atualizar usuário" %>
	<%= link_to "Cancelar", @usuario %>
<% end %>

app/views/usuarios/index.html.erb
<% provide :titulo, "Usuários" %>
<% content_for :botoes do %>
	<li><%= link_to "Adicionar", new_usuario_path %></li>
<% end %>

<ul>
	<% @usuarios.each do |usuario| %>
		<li>
			<%= link_to "#{usuario.nome} - #{usuario.nome_completo}", usuario %>
			| <%= link_to "excluir", usuario, method: :delete,
				data: { confirm: "Tem certeza?" } %>
		</li>
	<% end %>
</ul>

app/views/usuarios/new.html.erb
<% provide :titulo, "Usuários (Novo)" %>
<% content_for :botoes do %>
	<li><%= link_to "Listar", usuarios_path %></li>
	<li><%= link_to "Adicionar", new_usuario_path %></li>
<% end %>

<%= form_for(@usuario) do |f| %>
	<%= render 'error_messages' %>

	<%= f.label :nome %>
	<%= f.text_field :nome %><br>

	<%= f.label :nome_completo, "Nome Completo" %>
	<%= f.text_field :nome_completo %><br>

	<%= f.label :password, "Senha" %>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation, "Confimar senha" %>
	<%= f.password_field :password_confirmation %><br>

	<%= f.submit "Criar usuário" %>
	<%= link_to "Cancelar", usuarios_path %>
<% end %>

app/views/usuarios/show.html.erb
<% provide :titulo, "Usuários (Detalhes)" %>
<% content_for :botoes do %>
	<li><%= link_to "Listar", usuarios_path %></li>
	<li><%= link_to "Adicionar", new_usuario_path %></li>
	<li><%= link_to "Excluir", @usuario, method: :delete,
		data: { confirm: "Tem certeza que deseja excluir '#{@usuario.nome}'?" } %></li>
	<li><%= link_to "Alterar", edit_usuario_path(params[:id]) %></li>
<% end %>

Nome: <%= @usuario.nome %><br>
Nome Completo: <%= @usuario.nome_completo %>