config/routes.rb
PasseLivre::Application.routes.draw do
  resources :pessoas
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]

  root 'sessions#new'

  match '/login',   to: 'sessions#new',     via: 'get'
  match '/logoff',  to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_cabecalho.html.erb
<header class="navbar">
	<div class="navbar-inner">
		<div class="container">
			<div id="logo">Passe Livre</div>
			<% if logado? %>
				<nav>
					<ul class="nav pull-right">				
						<% if usuario_atual.admin? %>
							<li><%= link_to "Usuários", usuarios_path %></li>
							<li><%= link_to "Pessoas", pessoas_path %></li> 
						<% end %>
						<li><%= link_to "Sair", logoff_path, method: "delete" %></li>
					</ul>
				</nav>
			<% end %>
		</div>
	</div>
</header>

app/views/layouts/_links.html.erb
<nav>
	<ul>
		
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Passe Livre</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/cabecalho' %>

<h1><%= yield :titulo %></h1>

<div class="navbar navbar-inner"><ul class="nav"><%= yield :botoes %></ul></div>

<div>
	<% flash.each do |key, value| %>
		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
	<% end %>
</div>
<div class="container">
	<%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>

</body>
</html>